apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appcatalog.fullname" . }}-nginx-conf
  labels:
    {{- include "appcatalog.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Values.nginx.config | indent 4 }}