{{- if .Values.supabase.anonKeySecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.supabase.anonKeySecret.name }}
type: Opaque
data:
  {{ .Values.supabase.anonKeySecret.key }}: "{{ .Values.supabase.anonKeySecret.value | b64enc }}"
{{- end }}
